pc:
  inquiryMail:
    caption: "お問い合わせメール"
    configurable: false
    sample:
      ja_JP: |
        以下の内容でお問い合わせを頂きました。
        
        ---------------------------------------------------
        {% if member_id %}SNS上の名前 ：{{ member_name }}
        メンバーID ：{{ member_id }}
        ---------------------------------------------------
        {% endif %}{% for key, value in details %}{{ key }}：{{ value }}
        {% endfor %}
        
  inquiryMailConfirm:
    caption: "お問い合わせ確認メール"
    configurable: false
    sample:
      ja_JP: |
        この度は{{ op_config.sns_name }}にお問い合わせありがとうございます。
        以下の内容にてお問い合わせを受け付けました。
        お問い合わせ内容、状況によっては数日のお時間を頂く場合がありますので、しばらくお待ちください。
        
        ※このメールはシステムにより自動送信しております。
        
        ---------------------------------------------------
        {% if member_id %}SNS上の名前 ：{{ member_name }}
        メンバーID ：{{ member_id }}
        ---------------------------------------------------
        {% endif %}{% for key, value in details %}{{ key }}：{{ value }}
        {% endfor %}


mobile:
  inquiryMail:
    caption: "お問い合わせメール"
    configurable: false
    sample:
      ja_JP: |
        以下の内容でお問い合わせを頂きました。
        
        ---------------------------------------------------
        {% if member_id %}SNS上の名前 ：{{ member_name }}
        メンバーID ：{{ member_id }}
        ---------------------------------------------------
        {% endif %}{% for key, value in details %}{{ key }}：{{ value }}
        {% endfor %}
        
  inquiryMailConfirm:
    caption: "お問い合わせ確認メール"
    configurable: false
    sample:
      ja_JP: |
        この度は{{ op_config.sns_name }}にお問い合わせありがとうございます。
        以下の内容にてお問い合わせを受け付けました。
        お問い合わせ内容、状況によっては数日のお時間を頂く場合がありますので、しばらくお待ちください。
        
        ※このメールはシステムにより自動送信しております。
        
        ---------------------------------------------------
        {% if member_id %}SNS上の名前 ：{{ member_name }}
        メンバーID ：{{ member_id }}
        ---------------------------------------------------
        {% endif %}{% for key, value in details %}{{ key }}：{{ value }}
        {% endfor %}
